// Parse Claude Code session transcripts into a single conversation forest.
//
// Three edge sources collapse into one tree:
//   - parentUuid inside a file  = conversation flow
//   - parentUuid fanout >= 2    = rewind branch
//   - forkedFrom across files   = session fork -- needs NO special handling,
//     because a forked file copies the parent's messages with identical uuids,
//     so global uuid dedup turns a fork into the same fanout as a rewind.

import { readdirSync, readFileSync, existsSync, statSync } from 'node:fs';
import { join, basename } from 'node:path';
import { homedir } from 'node:os';

export interface Ckpt {
  /** repo-relative or absolute paths tracked at this point */
  files: string[];
  /** backupFileName per file, resolved under ~/.claude/file-history/<session>/ */
  backups: { path: string; backup: string; version: number }[];
}

export interface Node {
  id: string;
  session: string;
  parent: string | null;
  kind: 'user' | 'assistant';
  ts: string;
  text: string;
  ckpt?: Ckpt;
  /** children, in first-seen order */
  kids: string[];
}

export interface Graph {
  nodes: Map<string, Node>;
  roots: string[];
  /** node uuid -> summary title (rare; older transcripts) */
  titles: Map<string, string>;
  /** sessionId -> the session's title, generated or user-set */
  sessionTitle: Map<string, string>;
  /** sessionId -> first turn the session actually owns (not a copied prefix) */
  sessionStart: Map<string, string>;
  stats: {
    files: number;
    lines: number;
    dropped: number; // duplicate uuids from forked copies
    branchPoints: number;
    checkpoints: number;
  };
}

// Where Claude Code keeps its state. Overridable: the location differs per
// machine, and CLAUDE_CONFIG_DIR moves it.
let CLAUDE_HOME = process.env.CLAUDE_CONFIG_DIR || join(homedir(), '.claude');

export function setClaudeHome(path: string) {
  CLAUDE_HOME = path.replace(/^~(?=$|\/)/, homedir());
}

/** Back to $CLAUDE_CONFIG_DIR, or ~/.claude when that is unset. */
export function resetClaudeHome() {
  CLAUDE_HOME = process.env.CLAUDE_CONFIG_DIR || join(homedir(), '.claude');
}

export function claudeHome(): string {
  return CLAUDE_HOME;
}

/** <claude home>/projects/<slug> for a working directory. */
export function projectDir(cwd: string): string {
  const slug = cwd.replace(/\//g, '-');
  return join(CLAUDE_HOME, 'projects', slug);
}

function textOf(msg: any): string {
  if (!msg) return '';
  const c = msg.content;
  if (typeof c === 'string') return c;
  if (!Array.isArray(c)) return '';
  const parts: string[] = [];
  for (const b of c) {
    if (!b || typeof b !== 'object') continue;
    if (b.type === 'text' && b.text) parts.push(b.text);
    else if (b.type === 'tool_use') parts.push(`[${b.name}]`);
    else if (b.type === 'tool_result') parts.push('[result]');
  }
  return parts.join(' ');
}

// Slash commands and skill loads are written as `user` records anchored to a
// `system` record rather than to the previous message, so they fan out exactly
// like a rewind. They are harness bookkeeping, not something the user typed.
const HARNESS = [
  /<command-(name|message|args)>/,
  /^Base directory for this skill:/,
  /<local-command-(stdout|caveat)>/,
  /^Caveat: The messages below were generated by the user while running local commands/,
  /^\[Request interrupted by user/,
];
function isHarnessNoise(text: string): boolean {
  const t = text.trim();
  return HARNESS.some((re) => re.test(t));
}

function isToolResultOnly(msg: any): boolean {
  const c = msg?.content;
  return Array.isArray(c) && c.length > 0 && c.every((b: any) => b?.type === 'tool_result');
}

function oneLine(s: string): string {
  // system-reminder blocks and hook noise dominate otherwise
  const t = s
    .replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, '')
    .replace(/<command-name>([^<]*)<\/command-name>/g, '$1')
    .replace(/<command-(message|args)>[\s\S]*?<\/command-\1>/g, '')
    .replace(/<local-command-(caveat|stdout)>[\s\S]*?<\/local-command-\1>/g, '')
    .replace(/<[^>]{1,40}>/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  return t;
}

export function loadProject(dir: string): Graph {
  if (!existsSync(dir)) throw new Error(`no such project dir: ${dir}`);
  const files = readdirSync(dir).filter((f) => f.endsWith('.jsonl')).sort();

  const nodes = new Map<string, Node>();
  const titles = new Map<string, string>();
  const sessionTitle = new Map<string, string>();
  const sessionStart = new Map<string, string>();
  // messageId -> snapshot, joined onto nodes after all files are read
  const snaps = new Map<string, Ckpt>();
  const seenMsgId = new Map<string, string>(); // message.id -> the node holding that turn
  const harnessUuids = new Set<string>();
  const harnessTs = new Map<string, string>();
  let lines = 0;
  let dropped = 0;

  // Pass 1: session start times, so dedup can prefer the original over a copy.
  const startOf = new Map<string, string>();
  const forkParent = new Map<string, string>();
  const parsed: { session: string; recs: any[] }[] = [];
  for (const f of files) {
    const session = basename(f, '.jsonl');
    const recs: any[] = [];
    for (const line of readFileSync(join(dir, f), 'utf8').split('\n')) {
      if (!line.trim()) continue;
      lines++;
      let d: any;
      try {
        d = JSON.parse(line);
      } catch {
        continue; // truncated tail on a live session
      }
      recs.push(d);
      if (d.forkedFrom?.sessionId) forkParent.set(session, d.forkedFrom.sessionId);
      const ts = d.timestamp;
      if (ts && (!startOf.has(session) || ts < startOf.get(session)!)) startOf.set(session, ts);
    }
    parsed.push({ session, recs });
  }


  // Original session first, so its copy of a shared uuid wins the dedup. A fork
  // copies its parent's prefix verbatim -- timestamps included -- so start time
  // alone ties; fork depth breaks the tie.
  const forkDepth = (s: string): number => {
    let d = 0;
    let cur = s;
    while (forkParent.has(cur) && d < 64) {
      cur = forkParent.get(cur)!;
      d++;
    }
    return d;
  };
  const rank = new Map(parsed.map((p) => [p.session, forkDepth(p.session)]));
  parsed.sort(
    (a, b) =>
      rank.get(a.session)! - rank.get(b.session)! ||
      (startOf.get(a.session) ?? '').localeCompare(startOf.get(b.session) ?? '') ||
      a.session.localeCompare(b.session),
  );

  for (const { session, recs } of parsed) {
    for (const d of recs) {
      // Titles live in their own records, keyed by session: `ai-title` is the
      // generated one, `custom-title` wins because the user set it. The last
      // record of each kind is the current one.
      if (d.type === 'ai-title' && d.aiTitle) {
        if (!sessionTitle.has(`custom:${d.sessionId}`)) sessionTitle.set(d.sessionId ?? session, d.aiTitle);
        continue;
      }
      if (d.type === 'custom-title' && d.customTitle) {
        sessionTitle.set(d.sessionId ?? session, d.customTitle);
        sessionTitle.set(`custom:${d.sessionId}`, '1');
        continue;
      }
      if (d.type === 'summary' && d.summary) {
        // summary rows point at a leaf; label the session that owns that leaf later
        titles.set(d.leafUuid, d.summary);
        continue;
      }
      if (d.type === 'file-history-snapshot' && d.snapshot?.messageId) {
        const tracked = d.snapshot.trackedFileBackups ?? {};
        // A tracked file can be recorded without a backup (deleted, or never
        // written); those entries carry a null backupFileName.
        const backups = Object.entries<any>(tracked)
          .filter(([, b]) => typeof b?.backupFileName === 'string')
          .map(([path, b]) => ({
            path,
            backup: join(CLAUDE_HOME, 'file-history', session, b.backupFileName),
            version: b.version,
          }));
        if (backups.length) snaps.set(d.snapshot.messageId, { files: backups.map((b) => b.path), backups });
        continue;
      }
      // Only real conversation turns become nodes. `attachment`, `system`, and
      // subagent sidechains fan out off shared parents and would otherwise
      // inflate the branch count ~8x.
      if (d.type !== 'user' && d.type !== 'assistant') continue;
      if (d.isSidechain) continue;
      if (!d.uuid) continue;
      // Parallel tool calls are stored as several records sharing one
      // message.id; keeping them all turns every parallel call into a fake
      // branch. Keep the first record of each assistant message.
      const mid = d.message?.id;
      if (d.type === 'assistant' && mid) {
        const first = seenMsgId.get(mid);
        if (first) {
          // Same turn, later block: fold its text into the node we already made
          // instead of dropping it, or a turn that opened with thinking would
          // be labelled `[thinking]` forever.
          const head = nodes.get(first);
          if (head) head.text = oneLine([head.text, oneLine(textOf(d.message))].filter(Boolean).join(' '));
          dropped++;
          continue;
        }
        seenMsgId.set(mid, d.uuid);
      }
      // tool_result carriers are transport, not user turns.
      if (d.type === 'user' && isToolResultOnly(d.message)) continue;
      const raw = textOf(d.message);
      if (d.type === 'user' && isHarnessNoise(raw)) {
        harnessUuids.add(d.uuid);
        harnessTs.set(d.uuid, d.timestamp ?? '');
        continue;
      }
      if (nodes.has(d.uuid)) {
        dropped++;
        continue;
      }
      nodes.set(d.uuid, {
        id: d.uuid,
        session,
        parent: d.parentUuid ?? null,
        kind: d.type,
        ts: d.timestamp ?? '',
        text: oneLine(raw),
        ckpt: undefined,
        kids: [],
      });
    }
  }

  let checkpoints = 0;
  for (const n of nodes.values()) {
    const c = snaps.get(n.id);
    if (c) {
      n.ckpt = c;
      checkpoints++;
    }
  }

  // Parents pointing at filtered-out records (attachments) must be lifted to the
  // nearest surviving ancestor, otherwise those subtrees become false roots.
  const parentIndex = new Map<string, string | null>(); // raw uuid -> raw parent
  const rawSession = new Map<string, string>();
  for (const { session, recs } of parsed)
    for (const d of recs)
      if (d.uuid && !parentIndex.has(d.uuid)) {
        parentIndex.set(d.uuid, d.parentUuid ?? null);
        rawSession.set(d.uuid, session);
      }

  // raw uuid where a lift ran out of surviving ancestors -> nodes stranded there
  const stranded = new Map<string, string[]>();
  const viaHarness: [string, string][] = [];
  for (const n of nodes.values()) {
    let p = n.parent;
    let lastRaw: string | null = null;
    let crossedHarness = false;
    let anchorTs = '';
    const seen = new Set<string>();
    while (p && !nodes.has(p)) {
      if (seen.has(p)) {
        p = null;
        break;
      }
      seen.add(p);
      if (harnessUuids.has(p) && !crossedHarness) {
        crossedHarness = true;
        anchorTs = harnessTs.get(p) || n.ts;
      }
      lastRaw = p;
      p = parentIndex.get(p) ?? null;
    }
    n.parent = p;
    if (crossedHarness) viaHarness.push([n.id, anchorTs]);
    else if (p === null && lastRaw) {
      const g = stranded.get(lastRaw) ?? [];
      g.push(n.id);
      stranded.set(lastRaw, g);
    }
  }

  // A slash command anchors its records to a `system` record instead of to the
  // previous message, so lifting through one leaves the conversation that
  // followed hanging off an ancestor far above -- a rewind that never happened.
  // Re-attach those to the turn that actually preceded them in the session.
  const byTime = new Map<string, Node[]>();
  for (const n of nodes.values()) {
    const g = byTime.get(n.session) ?? [];
    g.push(n);
    byTime.set(n.session, g);
  }
  for (const g of byTime.values()) g.sort((a, b) => a.ts.localeCompare(b.ts) || a.id.localeCompare(b.id));
  const isAncestor = (candidate: string, of: string): boolean => {
    let cur: string | null = candidate;
    const seen = new Set<string>();
    while (cur && !seen.has(cur)) {
      if (cur === of) return true;
      seen.add(cur);
      cur = nodes.get(cur)?.parent ?? null;
    }
    return false;
  };
  for (const [id, anchorTs] of viaHarness) {
    const n = nodes.get(id)!;
    const siblings = byTime.get(n.session)!;
    // Anchor on the turn that preceded the REMOVED record, not the one that
    // preceded this child: siblings of a rewind must stay siblings.
    let prev: Node | undefined;
    for (const s of siblings) {
      if (s.ts < (anchorTs || n.ts)) prev = s;
      else break;
    }
    // Guard against pointing a node at its own descendant.
    if (prev && !isAncestor(prev.id, n.id)) n.parent = prev.id;
    else if (n.parent === null) {
      const g = stranded.get(n.id) ?? [];
      stranded.set(n.id, g);
    }
  }

  // A rewind on the very first prompt branches off a record we filtered out
  // (the caveat/attachment preamble). Dropping it would split one tree into
  // several roots, so materialize the shared ancestor instead.
  for (const [raw, kids] of stranded) {
    if (kids.length < 2) continue;
    nodes.set(raw, {
      id: raw,
      session: rawSession.get(raw) ?? nodes.get(kids[0])!.session,
      parent: null,
      kind: 'user',
      ts: kids.map((k) => nodes.get(k)!.ts).sort()[0] ?? '',
      text: '(session start)',
      kids: [],
    });
    for (const k of kids) nodes.get(k)!.parent = raw;
  }

  const roots: string[] = [];
  for (const n of nodes.values()) if (n.parent === null) roots.push(n.id);

  for (const n of nodes.values()) if (n.parent) nodes.get(n.parent)!.kids.push(n.id);

  let branchPoints = 0;
  for (const n of nodes.values()) if (n.kids.length > 1) branchPoints++;

  roots.sort((a, b) => nodes.get(a)!.ts.localeCompare(nodes.get(b)!.ts));
  for (const k of [...sessionTitle.keys()]) if (k.startsWith('custom:')) sessionTitle.delete(k);

  // A branch copies its parent's prefix with the original timestamps, so the
  // file's earliest record is the PARENT's start. Date the session by the first
  // turn it actually owns; fall back to the file only when it owns none.
  for (const n of nodes.values()) {
    const seen = sessionStart.get(n.session);
    if (!seen || n.ts < seen) sessionStart.set(n.session, n.ts);
  }
  for (const [s, ts] of startOf) if (!sessionStart.has(s)) sessionStart.set(s, ts);

  return {
    nodes,
    roots,
    titles,
    sessionTitle,
    sessionStart,
    stats: { files: files.length, lines, dropped, branchPoints, checkpoints },
  };
}

export type Detail =
  /** one row per user turn; Claude's steps disappear entirely */
  | 'user'
  /** every message, Claude's thinking and tool calls included */
  | 'all'
  /** topology only: roots, branches, checkpoints, tips */
  | 'topology';

/** Which nodes survive as rows. */
export function keepSet(g: Graph, detail: Detail = 'user'): Set<string> {
  const keep = new Set<string>();
  if (detail === 'all') {
    for (const id of g.nodes.keys()) keep.add(id);
    return keep;
  }
  for (const n of g.nodes.values()) {
    // Claude's turns stay when they carry structure: a branch point (otherwise
    // the split appears to happen at the user turn above it) or a tip (else a
    // branch whose only content is Claude's reply vanishes without a trace).
    const interesting =
      n.parent === null ||
      n.kids.length !== 1 ||
      n.ckpt ||
      (detail === 'user' ? n.kind === 'user' : g.nodes.get(n.parent)!.kids.length > 1);
    if (interesting) keep.add(n.id);
  }
  return keep;
}

export interface ProjectDir {
  /** ~/.claude/projects/<slug> */
  dir: string;
  /** the working directory those sessions ran in */
  cwd: string;
  sessions: number;
  /** newest session file mtime, ISO */
  modified: string;
}

/**
 * Every project folder Claude Code has recorded sessions for. The slug cannot
 * be decoded back into a path (both separators become `-`), so the working
 * directory is read from the transcripts themselves.
 */
export function listProjects(): ProjectDir[] {
  const base = join(CLAUDE_HOME, 'projects');
  if (!existsSync(base)) return [];
  const out: ProjectDir[] = [];
  for (const name of readdirSync(base)) {
    const dir = join(base, name);
    let files: string[];
    try {
      files = readdirSync(dir).filter((f) => f.endsWith('.jsonl'));
    } catch {
      continue; // not a directory
    }
    if (!files.length) continue;
    let cwd = '';
    let modified = '';
    for (const f of files) {
      const path = join(dir, f);
      const st = statSync(path);
      const ts = new Date(st.mtimeMs).toISOString();
      if (ts > modified) modified = ts;
      if (cwd) continue;
      for (const line of readFileSync(path, 'utf8').split('\n')) {
        if (!line.trim()) continue;
        try {
          const d = JSON.parse(line);
          if (d.cwd) {
            cwd = d.cwd;
            break;
          }
        } catch {
          /* keep looking */
        }
      }
    }
    out.push({ dir, cwd: cwd || name, sessions: files.length, modified });
  }
  return out.sort((a, b) => b.modified.localeCompare(a.modified));
}
